services:
  API:
    build:
      context: ./API
    ports:
      - "16000:16000"
    depends_on:
      - mongodb
  
  FrontEnd:
    build:
      context: ./FrontEnd
    ports:
      - "16001:16001"
    depends_on:
      - API
  
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    depends_on:
      - seed
  
## falta acabar